version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: ""
    environment: 
      DB_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
  db-data: