CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY NOT NULL,
	email TEXT NOT NULL UNIQUE,
	username VARCHAR(20) NOT NULL UNIQUE,
	password CHAR(100) NOT NULL,
	registration_timestamp TIMESTAMP,
	rating REAL NOT NULL DEFAULT 1500
);
